/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `kotlin-dsl`
    `java`
    `idea`
    id("io.quarkus") version "3.8.2"
    `maven-publish`
}

group = "com.gradle.demos.quarkus.wiremock"
version = "1.0.0-SNAPSHOT"
description = "Demo: WireMock Dev Service for Quarkus"

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project

dependencies {
    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
    api(libs.io.quarkus.quarkus.arc)
    api(libs.io.quarkus.quarkus.resteasy.reactive)
    api(libs.io.quarkus.quarkus.rest.client.reactive.jackson)
    api(libs.io.quarkus.quarkus.resteasy.reactive.jackson)
    api(libs.io.quarkiverse.wiremock.quarkus.wiremock)

    testImplementation(libs.io.quarkus.quarkus.junit5)
    testImplementation(libs.io.quarkiverse.wiremock.quarkus.wiremock.test)
    testImplementation(libs.io.rest.assured.rest.assured) {
      exclude(group = "org.apache.groovy", module = "groovy")
      exclude(group = "org.apache.groovy", module = "groovy-xml")
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}


tasks.withType<Test> {
    useJUnitPlatform()
    systemProperty("java.util.logging.manager", "org.jboss.logmanager.LogManager")
}

